package bank.KontoPackage;

/**
* bank/KontoPackage/ENotEnoughMoneyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public final class ENotEnoughMoneyHolder implements org.omg.CORBA.portable.Streamable
{
  public bank.KontoPackage.ENotEnoughMoney value = null;

  public ENotEnoughMoneyHolder ()
  {
  }

  public ENotEnoughMoneyHolder (bank.KontoPackage.ENotEnoughMoney initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bank.KontoPackage.ENotEnoughMoneyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bank.KontoPackage.ENotEnoughMoneyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bank.KontoPackage.ENotEnoughMoneyHelper.type ();
  }

}
