package bank;

/**
* bank/MonitorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public final class MonitorHolder implements org.omg.CORBA.portable.Streamable
{
  public bank.Monitor value = null;

  public MonitorHolder ()
  {
  }

  public MonitorHolder (bank.Monitor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bank.MonitorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bank.MonitorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bank.MonitorHelper.type ();
  }

}
