package bank;


/**
* bank/MonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public interface MonitorOperations 
{
  void meldung (String msg);

  //Damit kann die Bank den Monitor beenden.
  void exit ();
} // interface MonitorOperations
