package bank.KontoPackage;

/**
* bank/KontoPackage/EInvalidAmountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public final class EInvalidAmountHolder implements org.omg.CORBA.portable.Streamable
{
  public bank.KontoPackage.EInvalidAmount value = null;

  public EInvalidAmountHolder ()
  {
  }

  public EInvalidAmountHolder (bank.KontoPackage.EInvalidAmount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bank.KontoPackage.EInvalidAmountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bank.KontoPackage.EInvalidAmountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bank.KontoPackage.EInvalidAmountHelper.type ();
  }

}
