package bank.KontoPackage;


/**
* bank/KontoPackage/EInvalidAmount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public final class EInvalidAmount extends org.omg.CORBA.UserException
{
  public String s = null;

  public EInvalidAmount ()
  {
    super(EInvalidAmountHelper.id());
  } // ctor

  public EInvalidAmount (String _s)
  {
    super(EInvalidAmountHelper.id());
    s = _s;
  } // ctor


  public EInvalidAmount (String $reason, String _s)
  {
    super(EInvalidAmountHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class EInvalidAmount
