package bank;


/**
* bank/KontoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public interface KontoOperations 
{
  double kontostand ();

  //Kontostand
  String kontonr ();

  //Kontonummer
  void einzahlen (double betrag) throws bank.KontoPackage.EInvalidAmount;
  void auszahlen (double betrag) throws bank.KontoPackage.EInvalidAmount, bank.KontoPackage.ENotEnoughMoney;
  void transfer (double betrag, bank.Konto toKonto) throws bank.KontoPackage.EInvalidAmount;
} // interface KontoOperations
