package bank.BankPackage;


/**
* bank/BankPackage/EKontoNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from bank.idl
* Mittwoch, 26. März 2014 15:55 Uhr MEZ
*/

public final class EKontoNotFound extends org.omg.CORBA.UserException
{
  public String s = null;

  public EKontoNotFound ()
  {
    super(EKontoNotFoundHelper.id());
  } // ctor

  public EKontoNotFound (String _s)
  {
    super(EKontoNotFoundHelper.id());
    s = _s;
  } // ctor


  public EKontoNotFound (String $reason, String _s)
  {
    super(EKontoNotFoundHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class EKontoNotFound
